# Generated by Django 2.2.24 on 2021-08-27 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('link', models.URLField(verbose_name='link')),
                ('up_vote', models.IntegerField(default=0, verbose_name='up Vote')),
                ('down_vote', models.IntegerField(default=0, verbose_name='down Vote')),
                ('archive', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified On')),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='text')),
                ('posted_on', models.DateTimeField(auto_now_add=True, verbose_name='posted On')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified On')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
